version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/WordAXDB/data:/var/lib/postgresql/data

  init-db:
    image: postgres
    depends_on:
      - postgres
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

