services:
  postgres:
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - /home/WordAXDB/data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d


