services:
  postgres:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
        POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - '5432:5432'
    volumes:
      - /home/WordAXDB/data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
